/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/sensor": {
    post: {
      responses: {
        /** OK */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["SensorData"];
        };
      };
    };
  };
  "/image": {
    post: {
      requestBody: {
        content: {
          "multipart/form-data": components["schemas"]["ImageData"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    SensorData: {
      gas?: number;
      humitidy?: number;
      pressure?: number;
      temperature?: number;
      light?: number;
      noise?: number;
    };
    ImageData: {
      file?: string;
      personDetected?: boolean;
      backpackDetected?: boolean;
      markerDetected?: boolean;
    };
  };
}

export interface operations {}

export interface external {}
